In [2]:
from gsw import *

In [2]:
%%time
n=10
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(n):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,fast_lst_sq=False))

Wall time: 90 ms


C:\Users\Ga Bo\Desktop\Master Thesis\GSWalk\gsw.py:215: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  u1=np.linalg.lstsq(B_t,-B[:,p])[0]
C:\Users\Ga Bo\Desktop\Master Thesis\GSWalk\gsw.py:216: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  u1=np.linalg.lstsq(B_t,-B[:,p])[0]


In [3]:
%%time
n=10
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(n):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,fast_lst_sq=True))

C:\Users\Ga Bo\Desktop\Master Thesis\GSWalk\gsw.py:408: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  sol=np.linalg.lstsq(m, i)


Wall time: 104 ms


In [3]:
%%time
n=10
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(n):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,no_matrix_mult=True,flag_issue=True))

[ 0.32077054 -0.6001634   0.67393234  1.          0.13469894 -0.03949953
 -0.19789766  0.61047221  0.58191698  0.40863182]
[ 0.64516467  0.21674403  1.          0.         -0.1073233   0.04073972
  0.1878325  -0.17886523  1.04622484  0.93589552]
[-1.4069851  -0.09100757  0.          0.          1.          0.03787471
 -0.75774735  0.48975877 -0.49047907 -0.79720843]
[-1.00745188 -0.22378796  0.          0.          1.          0.09357416
 -0.61958499  0.29680145  0.         -0.43535165]
[ 0.         -0.46391107  0.          0.          1.         -0.04708066
 -0.24774325  0.29975765  0.         -0.1107432 ]
[ 0.         -0.45685624  0.          0.          1.         -0.04744927
 -0.24182684  0.26905819  0.          0.        ]
[ 0.         -0.1337274   0.          0.          0.          0.1482161
  0.12298657  1.          0.          0.        ]
[ 0.          0.4388293   0.          0.          0.         -0.04820806
  1.          0.          0.          0.        ]
[ 0.         1.  

C:\Users\Ga Bo\Desktop\Master Thesis\GSWalk\gsw.py:435: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  sol=np.linalg.lstsq(m, i)
C:\Users\Ga Bo\Desktop\Master Thesis\GSWalk\gsw.py:232: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  u1=np.linalg.lstsq(B_t,-B[:,p])[0]


In [4]:
%%time
n=10
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(n):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,no_matrix_mult=True,flag_issue=False))

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
[0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0

In [19]:
%%time
n=100
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(10):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,fast_lst_sq=False))

Finished 'next_direction' in 0.03 secs
Finished 'next_direction' in 0.011 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.009 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.025 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.094 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.011 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.006 secs
F

Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.035 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.003 secs


Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs


Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.066 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs


Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.04 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
F

In [20]:
%%time
n=100
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(10):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,fast_lst_sq=True))

Finished 'next_direction' in 0.01 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.011 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
F

Finished 'next_direction' in 0.043 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs


Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.056 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs


Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.02 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
F

Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs


In [11]:
%%time
n=100
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(10):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,no_matrix_mult=True,flag_issue=True))

Finished 'next_direction' in 0.04 secs
Finished 'next_direction' in 0.01 secs
Finished 'next_direction' in 0.01 secs
Finished 'next_direction' in 0.009 secs
Finished 'next_direction' in 0.024 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.106 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.03 secs
Finished 'next_direction' in 0.011 secs
Finished 'next_direction' in 0.006 secs
Fini

Finished 'next_direction' in 0.015 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.111 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.017 secs
Finished 'next_direction' in 0.017 secs
Finished 'next_direction' in 0.018 secs
Finished 'next_direction' in 0.041 secs
Finished 'next_direction' in 0.016 secs
Finished 'next_direction' in 0.036 secs
Finished 'next_direction' in 0.018 secs
Finished 'next_direction' in 0.026 secs
Finished 'next_direction' in 0.02 secs
Finished 'next_direction' in 0.011 secs
Finished 'next_direction' in 0.016 secs
Finished 'next_direction' in 0.012 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.033 secs
Finished 'next_direction' in 0.009 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.006 secs
F

Finished 'next_direction' in 0.061 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.061 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.039 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.011 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.006 secs


Finished 'next_direction' in 0.043 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.028 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.037 secs
Finished 'next_direction' in 0.007 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.049 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.053 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.093 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.013 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.006 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.005 secs
Finished 'next_direction' in 0.005 secs


KeyboardInterrupt: 

In [18]:
%%time
n=100
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(10):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,no_matrix_mult=True,flag_issue=False))

Finished 'next_direction' in 0.023 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.014 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.008 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs


Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.004 secs


Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs


Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.003 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs


Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.004 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.002 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs
Finished 'next_direction' in 0.001 secs


In [4]:
%%time
n=200
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(n):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,fast_lst_sq=False))

C:\Users\Ga Bo\Desktop\Master Thesis\GSWalk\gsw.py:215: FutureWarning: `rcond` parameter will change to the default of machine precision times ``max(M, N)`` where M and N are the input matrix dimensions.
To use the future default and silence this warning we advise to pass `rcond=None`, to keep using the old, explicitly pass `rcond=-1`.
  u1=np.linalg.lstsq(B_t,-B[:,p])[0]


Wall time: 23min 35s


In [5]:
%%time
n=200
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(n):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,fast_lst_sq=True))

Wall time: 12min 5s


In [3]:
%%time
n=200
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(n):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,no_matrix_mult=True,flag_issue=False))

Wall time: 14min 27s


In [7]:
%%time
n=500
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(10):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,fast_lst_sq=True))

Wall time: 9min 24s


In [8]:
%%time
n=500
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(10):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,no_matrix_mult=True,flag_issue=False))

Wall time: 11min 45s


In [9]:
%%time
n=1000
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(1):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,fast_lst_sq=True))

Wall time: 9min 10s


In [10]:
%%time
n=1000
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(1):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,no_matrix_mult=True,flag_issue=False))

Wall time: 8min 18s


In [11]:
%%time
n=2000
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(1):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,fast_lst_sq=True))

Wall time: 1h 25min 8s


In [12]:
%%time
n=2000
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(1):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,no_matrix_mult=True,flag_issue=False))

Wall time: 1h 22min 21s


In [13]:
%%time
#Now with adapted code which should be faster
n=500
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(10):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,fast_lst_sq=True))

Wall time: 10min 49s


In [14]:
%%time
#Now with adapted code which should be faster
n=500
v=sample_from_sphere(n)
v=sample_from_ball(n,d=n)
gsw_xs=[]
for i in range(10):
    gsw_xs.append(gram_schmidt_walk(v,np.zeros(n),plot=False,debug=False,no_matrix_mult=True,flag_issue=False))

Wall time: 11min 58s
